[project]
authors = ["Mitchell Robert Vollger <mrvollger@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "FIRE"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]
fmt = "ruff format workflow/ && taplo format pixi.toml && snakefmt workflow/"
test = { cmd = [
  "snakemake",
] }
snakemake = "snakemake"

[dependencies]
conda = "*"
snakemake = "==8.21"
snakefmt = "*"
ruff = "*"
awscli = "2.22"
taplo = "*"

[pypi-dependencies]
snakemake-executor-plugin-slurm = "*"
