name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: ". --check --verbose"

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint"

  run-workflow:
    needs: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test CI
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: workflow/Snakefile
